"""add_max_min_price_and_market_state

Revision ID: 018bbde07f40
Revises: c1a2b3c4d5e6
Create Date: 2025-12-25 13:09:41.682801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018bbde07f40'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('snapshot_count', sa.Integer(), nullable=False),
    sa.Column('after_hours_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('market_day_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_price_event_ticker_created_at'), table_name='price_event')
    op.add_column('stock', sa.Column('max_price', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('min_price', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_stock_snapshot_ticker_created_at'), table_name='stock_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_snapshot_ticker_created_at'), 'stock_snapshot', ['ticker', 'created_at'], unique=False)
    op.drop_column('stock', 'min_price')
    op.drop_column('stock', 'max_price')
    op.create_index(op.f('ix_price_event_ticker_created_at'), 'price_event', ['ticker', 'created_at'], unique=False)
    op.drop_table('market_state')
    # ### end Alembic commands ###
